### ISSUE TITLE
Failure to start after upgrade to v8.50

### ISSUE THREAD

**Issue by c2mfj** [MLB-LED-Scoreboard/mlb-led-scoreboard#636]
After upgrading to version v8.5 I am getting the following errors that seems related to the changes made in the new version. Strangely my 2nd scoreboard on the latest version does not receive the same error.

I've re-run the install script a couple of times but no luck so far.

`ERROR (05:14:50): Error while fetching game 777199 uniform data
Traceback (most recent call last):
  File "/opt/mlb-led-scoreboard/data/uniforms.py", line 41, in update
    data_u = statsapi.get("game_uniforms", {"gamePks": self.game_id, "fields": API_FIELDS}, request_kwargs={"headers": data.headers.API_HEADERS})["uniforms"][0]
TypeError: get() got an unexpected keyword argument 'request_kwargs'

ERROR (05:14:50): Networking Error while refreshing the current game data.
Traceback (most recent call last):
  File "/opt/mlb-led-scoreboard/data/game.py", line 59, in update
    live_data = statsapi.get("game", {"gamePk": self.game_id, "fields": API_FIELDS} | testing_params, request_kwargs={"headers": data.headers.API_HEADERS} )
TypeError: get() got an unexpected keyword argument 'request_kwargs'

ERROR (05:14:51): Failed to refresh important dates
Traceback (most recent call last):
  File "/opt/mlb-led-scoreboard/data/dates.py", line 10, in __init__
    data_d = statsapi.get("season", {"sportId": 1, "seasonId": year}, request_kwargs={"headers": data.headers.API_HEADERS})
TypeError: get() got an unexpected keyword argument 'request_kwargs'

ERROR (05:14:51): Failed to refresh standings.
Traceback (most recent call last):
  File "/opt/mlb-led-scoreboard/data/standings.py", line 54, in update
    divisons_data = statsapi.get("standings", season_params, request_kwargs={"headers": data.headers.API_HEADERS})
TypeError: get() got an unexpected keyword argument 'request_kwargs'

Exception in thread render_thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mlb-led-scoreboard/./main.py", line 158, in __render_main
    MainRenderer(matrix, data).render()
  File "/opt/mlb-led-scoreboard/renderers/main.py", line 47, in render
    self.__render_gameday()
  File "/opt/mlb-led-scoreboard/renderers/main.py", line 94, in __render_gameday
    self.__draw_game()
  File "/opt/mlb-led-scoreboard/renderers/main.py", line 103, in __draw_game
    scoreboard = Scoreboard(game)
  File "/opt/mlb-led-scoreboard/data/scoreboard/__init__.py", line 20, in __init__
    game.away_abbreviation(), game.away_score(), game.away_name(), game.away_hits(), game.away_errors(), game.away_record(), game.away_special_uniforms()
AttributeError: 'NoneType' object has no attribute 'away_abbreviation'

ERROR (05:14:53): Untrapped error in main!
Traceback (most recent call last):`

**Comment by WardBrian** [comment]
Seems similar to #633 where the virtual environment didn't update properly. This error would happen if an older version of statsapi was used

**Comment by WardBrian** [comment]
Hm, something odd is happening then.

We should definitely update our manual version check
https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/blob/8142d4e42bddffba57e08be14e28eaef6f74de39/main.py#L13-L17
