### ISSUE TITLE
Starting up with --emulator arg throws error

### ISSUE THREAD

**Issue by unwound29** [MLB-LED-Scoreboard/mlb-led-scoreboard#779]
In the current version, starting up the app with `--emulated` throws an error:

```
unclebus@mlb-scoreboard-pi:~/mlb-led-scoreboard $ sudo ./main.py --emulated
[2026-08-31 23:15:23] [bullpen] [WARNING]: Config file /home/unclebus/mlb-led-scoreboard/colors/teams.json not found. Using default values for this file.
[2026-08-31 23:15:23] [bullpen] [INFO]: Custom 'scoreboard.json' colors found. Merging with default reference colors.
Traceback (most recent call last):
  File "/home/unclebus/mlb-led-scoreboard/./main.py", line 126, in <module>
    config.matrix_options.emulator_title = f"{SCRIPT_NAME} v{SCRIPT_VERSION}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'rgbmatrix.core.RGBMatrixOptions' object has no attribute 'emulator_title'
```

Claude's got a temporary solution of setting the driver mode early in main.py, but this might not be a proper fix considering all scenarios and modes. 

<img width="1286" height="758" alt="Image" src="https://github.com/user-attachments/assets/5e4adcb3-1777-4f26-99b0-88f8a929e1bb" />

**Comment by mcangeli** [comment]
I'm running this on a headless Pi5 with emulator only and it starts and runs fine. (It was just installed on the pi on friday of last week...

Are you running this with a matrix attached? 
If not, did you install it as emulator-only??

**Comment by mcangeli** [comment]
Also, do you have an emulator_config.json file in your mlb-led-scoreboard directory?

**Comment by ty-porter** [comment]
I think this was introduced in #702, and we made a related fix in #745 that could have contributed

Specifically, I think it's only noticeable on Pi hardware installed with `rpi-rgb-led-matrix` when using `--emulated`. Desktop emulation obviously can't compile that and `--emulator-only` sidesteps installing that library

The root cause of this is a partially initialized driver.

A little background: the driver wraps either `rpi-rgb-led-matrix` or `RGBMatrixEmulator`, which implements the same interface. It's configurable, so you can set the mode to emulation if you have hardware available, or if the hardware loads fail, it falls back to emulation automatically. We default to hardware mode. This is important, because it's the root of the problem.

#702 introduced the ability to store the matrix options (like `--emulated`) within the JSON config. One weird thing is one of the options is `--config`, where we allow you to set the path to the JSON config. This creates a circular dependency -- we need the CLI args to load the config to override the CLI args. That means we don't have the final value of the `--emulated` flag until well after config has started initializing.

And finally, the config class imports `RGBMatrixOptions` from the driver, which needs to be _fully_ initialized before importing anything.

---

So what happens is this:

1. Pass `--emulated` to an RPI with `rpi-rgb-led-matrix` installed.
2. Imports the driver, and implicitly sets the driver mode to `HARDWARE` since the real matrix driver is present and loadable
3. Start to initialize a `Config()` object
4. Importing the config object loads the partially initialized driver set to hardware mode.
5. Import the `RGBMatrixOptions` class from `rpi-rgb-led-matrix` library. It _should_ be imported from `RGBMatrixEmulator`
6. We now read the CLI arguments, load the JSON config, and apply any defaults from the JSON. Final value of `--emulated` is now known and set to `SOFTWARE_EMULATION`
7. Config initialization is finalized
8. We set the driver mode to `config.emulated`
9. We now try to set emulation options on a hardware options object, because the driver is now fully initialized in emulation mode.
10. Crash noted above

If you're on a platform without `rpi-rgb-led-matrix` (either non-RPI or installed with `--emulation-only`), step 2 is different:  the driver mode is defaulted to `SOFTWARE_EMULATION` since the real matrix driver doesn't exist.

**Comment by ty-porter** [comment]
Should be fixed in v9.2.2
